In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date

In [3]:
from prophet import Prophet
from prophet.diagnostics import performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.diagnostics import cross_validation

c:\Users\Windows 10\Desktop\rosman-store-project\forecast-sales\.salesvenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [27]:
df = pd.read_csv('./data/train.csv')
df['Date'] = pd.to_datetime(df['Date'])

C:\Users\Windows 10\AppData\Local\Temp\ipykernel_9608\2732287264.py:1: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/train.csv')

In [29]:
agg_df.head()

        Date    Sales
0 2013-01-01    97235
1 2013-01-02  6949829
2 2013-01-03  6347820
3 2013-01-04  6638954
4 2013-01-05  5951593

In [ ]:
# 2013-01-01 00:00:00 inicio
# 2015-07-31 00:00:00 fim

In [21]:
forecast_start_date = (date(2015,7,1)).strftime("%Y-%m-%d") 
print(forecast_start_date)

prediction_days = 30

2015-07-01

In [30]:
df_copy = agg_df.copy()
df_copy = df_copy.rename(columns={'Date': 'ds', 'Sales': 'y'})
df_copy[['y']] = df_copy[['y']].apply(pd.to_numeric)

train_set = df_copy[(df_copy['ds'] < forecast_start_date) ]

In [38]:
m = Prophet()
m.fit(train_set)
df_cv = cross_validation(m, initial='365 days', period='30 days', horizon = '30 days')

18:27:24 - cmdstanpy - INFO - Chain [1] start processing
18:27:24 - cmdstanpy - INFO - Chain [1] done processing
Seasonality has period of 365.25 days which is larger than initial window. Consider increasing initial.
  0%|          | 0/18 [00:00<?, ?it/s]18:27:26 - cmdstanpy - INFO - Chain [1] start processing
18:27:26 - cmdstanpy - INFO - Chain [1] done processing
  6%|▌         | 1/18 [00:00<00:08,  1.89it/s]18:27:26 - cmdstanpy - INFO - Chain [1] start processing
18:27:26 - cmdstanpy - INFO - Chain [1] done processing
 11%|█         | 2/18 [00:00<00:07,  2.06it/s]18:27:27 - cmdstanpy - INFO - Chain [1] start processing
18:27:27 - cmdstanpy - INFO - Chain [1] done processing
 17%|█▋        | 3/18 [00:01<00:07,  2.13it/s]18:27:27 - cmdstanpy - INFO - Chain [1] start processing
18:27:27 - cmdstanpy - INFO - Chain [1] done processing
 22%|██▏       | 4/18 [00:01<00:06,  2.15it/s]18:27:28 - cmdstanpy - INFO - Chain [1] start processing
18:27:28 - cmdstanpy - INFO - Chain [1] done processing
 28%|██▊       | 5/18 [00:02<00:06,  2.11it/s]18:27:28 - cmdstanpy - INFO - Chain [1] start processing
18:27:28 - cmdstanpy - INFO - Chain [1] done processing
 33%|███▎      | 6/18 [00:02<00:05,  2.15it/s]18:27:29 - cmdstanpy - INFO - Chain [1] start processing
18:27:29 - cmdstanpy - INFO - Chain [1] done processing
 39%|███▉      | 7/18 [00:03<00:05,  2.19it/s]18:27:29 - cmdstanpy - INFO - Chain [1] start processing
18:27:29 - cmdstanpy - INFO - Chain [1] done processing
 44%|████▍     | 8/18 [00:03<00:04,  2.19it/s]18:27:29 - cmdstanpy - INFO - Chain [1] start processing
18:27:30 - cmdstanpy - INFO - Chain [1] done processing
 50%|█████     | 9/18 [00:04<00:04,  2.25it/s]18:27:30 - cmdstanpy - INFO - Chain [1] start processing
18:27:30 - cmdstanpy - INFO - Chain [1] done processing
 56%|█████▌    | 10/18 [00:04<00:03,  2.27it/s]18:27:30 - cmdstanpy - INFO - Chain [1] start processing
18:27:30 - cmdstanpy - INFO - Chain [1] done processing
 61%|██████    | 11/18 [00:05<00:03,  2.29it/s]18:27:31 - cmdstanpy - INFO - Chain [1] start processing
18:27:31 - cmdstanpy - INFO - Chain [1] done processing
 67%|██████▋   | 12/18 [00:05<00:03,  1.84it/s]18:27:31 - cmdstanpy - INFO - Chain [1] start processing
18:27:32 - cmdstanpy - INFO - Chain [1] done processing
 72%|███████▏  | 13/18 [00:06<00:02,  1.89it/s]18:27:32 - cmdstanpy - INFO - Chain [1] start processing
18:27:32 - cmdstanpy - INFO - Chain [1] done processing
 78%|███████▊  | 14/18 [00:06<00:02,  1.91it/s]18:27:33 - cmdstanpy - INFO - Chain [1] start processing
18:27:33 - cmdstanpy - INFO - Chain [1] done processing
 83%|████████▎ | 15/18 [00:07<00:01,  1.94it/s]18:27:33 - cmdstanpy - INFO - Chain [1] start processing
18:27:33 - cmdstanpy - INFO - Chain [1] done processing
 89%|████████▉ | 16/18 [00:07<00:01,  1.96it/s]18:27:33 - cmdstanpy - INFO - Chain [1] start processing
18:27:34 - cmdstanpy - INFO - Chain [1] done processing
 94%|█████████▍| 17/18 [00:08<00:00,  2.06it/s]18:27:34 - cmdstanpy - INFO - Chain [1] start processing
18:27:34 - cmdstanpy - INFO - Chain [1] done processing
100%|██████████| 18/18 [00:08<00:00,  2.08it/s]

In [39]:
df_p = performance_metrics(df_cv)

In [46]:
df_p.head(30)

,horizon,mse,rmse,mae,mape,mdape,smape,coverage
0,3 days,4.351563e+12,2.086040e+06,1.599667e+06,1.062247,0.204595,0.360113,0.740741
1,4 days,5.402902e+12,2.324414e+06,1.681373e+06,1.692092,0.200105,0.425149,0.703704
2,5 days,5.667292e+12,2.380608e+06,1.734462e+06,1.733268,0.208132,0.406924,0.722222
3,6 days,5.453316e+12,2.335234e+06,1.638391e+06,1.699417,0.246857,0.412130,0.796296
4,7 days,3.679384e+12,1.918172e+06,1.436377e+06,1.130214,0.230143,0.350475,0.851852
5,8 days,2.382424e+12,1.543510e+06,1.244594e+06,0.469148,0.208081,0.328227,0.851852
6,9 days,2.011840e+12,1.418393e+06,1.140838e+06,0.429958,0.186297,0.311346,0.870370
7,10 days,1.828681e+12,1.352287e+06,1.068341e+06,0.517870,0.153540,0.312311,0.888889
8,11 days,1.745719e+12,1.321257e+06,9.960596e+05,0.513859,0.132554,0.323126,0.907407
9,12 days,2.696238e+12,1.642023e+06,1.117999e+06,1.123471,0.139563,0.322459,0.870370
10,13 days,3.366439e+12,1.834786e+06,1.196801e+06,1.443121,0.153886,0.371721,0.851852
11,14 days,3.745265e+12,1.935269e+06,1.336696e+06,1.471504,0.170288,0.367204,0.814815
12,15 days,4.178004e+12,2.044017e+06,1.396532e+06,1.444142,0.182353,0.394222,0.814815
13,16 days,3.566457e+12,1.888507e+06,1.346726e+06,1.058654,0.191773,0.380340,0.851852
14,17 days,3.286356e+12,1.812831e+06,1.309708e+06,1.090179,0.180676,0.375943,0.870370
15,18 days,1.879058e+12,1.370787e+06,1.148287e+06,0.470472,0.175534,0.380069,0.888889
16,19 days,2.022261e+12,1.422062e+06,1.207409e+06,0.430416,0.191133,0.338210,0.870370
17,20 days,1.951246e+12,1.396870e+06,1.159873e+06,0.383045,0.197685,0.344302,0.907407
18,21 days,2.149597e+12,1.466150e+06,1.189787e+06,0.317267,0.214767,0.269730,0.907407
19,22 days,1.916854e+12,1.384505e+06,1.111933e+06,0.303098,0.191269,0.280241,0.907407
20,23 days,3.236014e+12,1.798892e+06,1.230100e+06,1.513389,0.191843,0.359081,0.888889
21,24 days,5.299577e+12,2.302081e+06,1.453807e+06,2.659722,0.189874,0.446737,0.814815
22,25 days,6.194064e+12,2.488788e+06,1.506766e+06,3.191662,0.176426,0.500729,0.814815
23,26 days,4.865774e+12,2.205850e+06,1.369122e+06,1.930815,0.140439,0.390232,0.814815
24,27 days,2.522028e+12,1.588089e+06,1.049164e+06,0.811430,0.121452,0.351650,0.907407
25,28 days,2.178621e+12,1.476015e+06,1.129947e+06,0.291273,0.146018,0.306186,0.888889
26,29 days,3.359722e+12,1.832954e+06,1.423256e+06,0.337161,0.200386,0.353509,0.796296
27,30 days,6.301080e+12,2.510195e+06,1.896633e+06,2.039356,0.234343,0.465893,0.703704

In [ ]:
# print(df_cv['ds'].min())
# print(df_cv['ds'].max())

# 2014-01-07 00:00:00
# 2015-06-30 00:00:00

2014-01-07 00:00:00
2015-06-30 00:00:00

In [43]:
df_cv['mape'] = (df_cv['y']-df_cv['yhat'])/(df_cv['y'])*100
df_cv['overestimate'] = df_cv['yhat'] > df_cv['y'] 

df_cv.sort_values('mape',ascending=False).head(10)

,ds,yhat,yhat_lower,yhat_upper,y,cutoff,mape,overestimate
362,2015-01-04,-1.387213e+06,-3.668544e+06,7.979432e+05,197193,2015-01-01,803.479999,False
369,2015-01-11,-1.251774e+06,-3.672602e+06,9.205480e+05,183367,2015-01-01,782.660389,False
5,2014-01-12,-1.026388e+06,-3.312730e+06,1.285275e+06,175744,2014-01-06,684.024252,False
376,2015-01-18,-7.229591e+05,-2.948391e+06,1.505511e+06,195778,2015-01-01,469.274925,False
12,2014-01-19,-6.109279e+05,-2.940540e+06,1.822644e+06,175778,2014-01-06,447.556538,False
306,2014-11-09,-5.713088e+05,-2.895870e+06,1.569935e+06,177774,2014-11-02,421.368008,False
271,2014-10-05,-6.319584e+05,-2.960303e+06,1.725619e+06,225796,2014-10-03,379.880234,False
278,2014-10-12,-5.646801e+05,-3.129680e+06,1.551162e+06,240423,2014-10-03,334.869430,False
383,2015-01-25,-3.777970e+05,-2.757002e+06,1.963323e+06,179028,2015-01-01,311.026763,False
285,2014-10-19,-3.927855e+05,-2.762459e+06,1.793634e+06,204991,2014-10-03,291.611094,False