In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date

from prophet import Prophet
from prophet.diagnostics import performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.diagnostics import cross_validation

from utils import extrair_feriados_prophet, calcular_metricas_completas, executar_pipeline_otimizacao

c:\Users\Windows 10\Desktop\rosman-store-project\sales-forecast-with-prophet\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [26]:
df = pd.read_csv("../data/resultados_otimizacao_legado.csv", sep=",", on_bad_lines="skip")
df_01 = pd.read_csv("../data/resultados_otimizacao.csv", sep=",")

In [18]:
df[df['metodo'] == 'Holdout'].head(50)

,data_execucao,metodo,changepoint_prior_scale,seasonality_mode,seasonality_prior_scale,MSE,RMSE,MAE,MAPE,MDAPE,SMAPE,tempo_execucao
0,2026-07-07 23:52:04,Holdout,0.01,additive,0.1,160088.309796,400.110372,314.151595,0.066333,0.052109,0.324879,1.81
1,2026-07-07 23:52:05,Holdout,0.01,additive,1.0,166214.611283,407.694262,321.612264,0.067587,0.052444,0.326208,0.43
2,2026-07-07 23:52:06,Holdout,0.01,additive,10.0,166341.027123,407.849270,321.155317,0.067395,0.052172,0.326064,0.48
3,2026-07-07 23:52:07,Holdout,0.01,multiplicative,0.1,138198.962283,371.751210,276.846381,0.064660,0.043085,0.323355,0.51
4,2026-07-07 23:52:08,Holdout,0.01,multiplicative,1.0,139812.060253,373.914509,279.913732,0.065306,0.043853,0.323957,0.40
5,2026-07-07 23:52:09,Holdout,0.01,multiplicative,10.0,136748.024646,369.794571,277.004094,0.064243,0.044307,0.322970,0.37
6,2026-07-07 23:52:10,Holdout,0.10,additive,0.1,141378.621693,376.003486,293.285296,0.064125,0.055675,0.321966,0.43
7,2026-07-07 23:52:11,Holdout,0.10,additive,1.0,141457.725123,376.108661,293.309841,0.064127,0.055678,0.321962,0.46
8,2026-07-07 23:52:12,Holdout,0.10,additive,10.0,141573.798449,376.262938,293.458502,0.064127,0.055618,0.321974,0.46
9,2026-07-07 23:52:13,Holdout,0.10,multiplicative,0.1,142077.403348,376.931563,274.975554,0.065894,0.043974,0.324765,0.45
10,2026-07-07 23:52:14,Holdout,0.10,multiplicative,1.0,141850.227481,376.630094,275.599410,0.065921,0.043671,0.324753,0.45
11,2026-07-07 23:52:14,Holdout,0.10,multiplicative,10.0,139510.019791,373.510401,273.066074,0.065376,0.041540,0.324154,0.46
12,2026-07-07 23:52:15,Holdout,0.50,additive,0.1,142792.594389,377.879074,294.386508,0.063906,0.054658,0.321904,0.45
13,2026-07-07 23:52:16,Holdout,0.50,additive,1.0,142058.510709,376.906501,293.719596,0.063947,0.055194,0.321887,0.56
14,2026-07-07 23:52:17,Holdout,0.50,additive,10.0,142473.514079,377.456639,294.096378,0.063931,0.054921,0.321903,0.67
15,2026-07-07 23:52:19,Holdout,0.50,multiplicative,0.1,157893.227663,397.357808,281.881884,0.068369,0.048809,0.327514,0.50
16,2026-07-07 23:52:20,Holdout,0.50,multiplicative,1.0,152682.749638,390.746401,278.394475,0.067155,0.044191,0.326238,0.70
17,2026-07-07 23:52:21,Holdout,0.50,multiplicative,10.0,150667.409687,388.159001,276.957370,0.066553,0.042312,0.325621,0.83

In [25]:
df[df['metodo'] == 'Validacao Cruzada'].head(100)

,data_execucao,metodo,changepoint_prior_scale,seasonality_mode,seasonality_prior_scale,MSE,RMSE,MAE,MAPE,MDAPE,SMAPE,tempo_execucao
18,2026-07-08 00:03:53,Validacao Cruzada,0.01,additive,0.1,714.225906,542.503925,NaN,0.125096,0.757516,18.17,NaN
19,2026-07-08 00:04:04,Validacao Cruzada,0.01,additive,1.0,708.720406,537.227315,NaN,0.123456,0.765359,10.44,NaN
20,2026-07-08 00:04:17,Validacao Cruzada,0.01,additive,10.0,708.205733,536.478640,NaN,0.123853,0.756209,12.69,NaN
21,2026-07-08 00:04:38,Validacao Cruzada,0.01,multiplicative,0.1,713.618516,526.289397,NaN,0.126868,0.758824,20.24,NaN
22,2026-07-08 00:04:51,Validacao Cruzada,0.01,multiplicative,1.0,717.123801,530.006496,NaN,0.126527,0.758824,11.94,NaN
23,2026-07-08 00:05:02,Validacao Cruzada,0.01,multiplicative,10.0,707.700605,521.017705,NaN,0.124736,0.766667,10.59,NaN
24,2026-07-08 00:05:13,Validacao Cruzada,0.10,additive,0.1,726.645058,552.862188,NaN,0.134552,0.736601,11.10,NaN
25,2026-07-08 00:05:26,Validacao Cruzada,0.10,additive,1.0,732.680895,556.619673,NaN,0.134263,0.729412,11.86,NaN
26,2026-07-08 00:05:37,Validacao Cruzada,0.10,additive,10.0,730.273247,555.687396,NaN,0.133492,0.733333,11.34,NaN
27,2026-07-08 00:05:50,Validacao Cruzada,0.10,multiplicative,0.1,858.044923,624.888739,NaN,0.152120,0.694771,12.33,NaN
28,2026-07-08 00:06:03,Validacao Cruzada,0.10,multiplicative,1.0,856.442293,624.684853,NaN,0.152482,0.692810,12.00,NaN
29,2026-07-08 00:06:15,Validacao Cruzada,0.10,multiplicative,10.0,855.774904,625.033257,NaN,0.152001,0.692810,12.25,NaN
30,2026-07-08 00:06:31,Validacao Cruzada,0.50,additive,0.1,829.329552,642.120774,NaN,0.151848,0.673203,15.04,NaN
31,2026-07-08 00:06:46,Validacao Cruzada,0.50,additive,1.0,832.145982,645.860011,NaN,0.150398,0.678431,14.59,NaN
32,2026-07-08 00:06:58,Validacao Cruzada,0.50,additive,10.0,834.288090,647.155827,NaN,0.151365,0.673203,11.48,NaN
33,2026-07-08 00:07:13,Validacao Cruzada,0.50,multiplicative,0.1,1054.927998,762.533030,NaN,0.193710,0.619608,14.34,NaN
34,2026-07-08 00:07:27,Validacao Cruzada,0.50,multiplicative,1.0,1066.828705,768.825619,NaN,0.192945,0.625490,13.64,NaN
35,2026-07-08 00:07:42,Validacao Cruzada,0.50,multiplicative,10.0,1063.624443,766.333293,NaN,0.192503,0.639216,14.46,NaN

In [27]:
df_01[df_01['metodo'] == 'Validacao Cruzada'].head(100)

,data_execucao,metodo,parametros,rmse,mae,mape,mdape,coverage,tempo_execucao
0,2026-07-08 00:40:53,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'daily_seaso...",705.992189,534.443161,NaN,0.123806,0.764052,9.10
1,2026-07-08 00:41:02,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'daily_seaso...",717.614532,544.556200,NaN,0.125307,0.752941,9.37
2,2026-07-08 00:41:12,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'daily_seaso...",718.326890,544.951416,NaN,0.125318,0.754902,8.92
3,2026-07-08 00:41:21,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'daily_seaso...",705.264591,519.453781,NaN,0.124818,0.769935,8.87
4,2026-07-08 00:41:30,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'daily_seaso...",714.310621,525.297424,NaN,0.125662,0.767974,8.80
5,2026-07-08 00:41:40,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'daily_seaso...",707.802467,520.508675,NaN,0.122967,0.771242,9.38
6,2026-07-08 00:41:51,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'daily_season...",730.392800,555.521836,NaN,0.134157,0.728758,10.84
7,2026-07-08 00:42:01,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'daily_season...",729.555011,554.940878,NaN,0.134185,0.732680,9.59
8,2026-07-08 00:42:12,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'daily_season...",729.858437,555.136031,NaN,0.133926,0.733333,9.86
9,2026-07-08 00:42:22,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'daily_season...",896.200601,649.010440,NaN,0.158693,0.675163,9.57
10,2026-07-08 00:42:33,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'daily_season...",942.391491,682.623456,NaN,0.167770,0.654902,10.52
11,2026-07-08 00:42:43,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'daily_season...",960.628514,693.670425,NaN,0.172562,0.652288,10.32
12,2026-07-08 00:42:55,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'daily_season...",830.699729,643.664691,NaN,0.151459,0.671895,11.09
13,2026-07-08 00:43:06,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'daily_season...",834.329983,648.954809,NaN,0.152593,0.667974,10.75
14,2026-07-08 00:43:17,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'daily_season...",832.017067,645.604811,NaN,0.151764,0.670588,10.88
15,2026-07-08 00:43:32,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'daily_season...",1081.199028,761.491177,NaN,0.185236,0.695425,14.29
16,2026-07-08 00:43:48,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'daily_season...",1124.919292,781.478573,NaN,0.184298,0.799346,15.92
17,2026-07-08 00:44:06,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'daily_season...",1149.057717,797.231449,NaN,0.186165,0.836601,17.12
18,2026-07-08 00:50:04,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'seasonality...",704.647308,532.953864,NaN,0.122542,0.761438,9.73
19,2026-07-08 00:50:13,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'seasonality...",717.836701,543.704135,NaN,0.125665,0.757516,8.15
20,2026-07-08 00:50:21,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'seasonality...",712.796598,539.272135,NaN,0.123749,0.769935,7.49
21,2026-07-08 00:50:28,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'seasonality...",715.924552,521.551881,NaN,0.127405,0.762745,7.24
22,2026-07-08 00:50:37,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'seasonality...",710.897499,521.627792,NaN,0.125449,0.760784,8.18
23,2026-07-08 00:50:45,Validacao Cruzada,"{'changepoint_prior_scale': 0.01, 'seasonality...",713.432057,523.775010,NaN,0.126788,0.762092,7.60
24,2026-07-08 00:50:56,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'seasonality_...",730.076486,555.139403,NaN,0.134612,0.730719,11.29
25,2026-07-08 00:51:16,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'seasonality_...",728.870100,554.816347,NaN,0.133756,0.730719,19.41
26,2026-07-08 00:51:28,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'seasonality_...",730.995609,555.724619,NaN,0.134267,0.732026,11.94
27,2026-07-08 00:51:41,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'seasonality_...",986.651283,712.907693,NaN,0.177743,0.632680,12.13
28,2026-07-08 00:52:00,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'seasonality_...",971.438677,707.583752,NaN,0.175985,0.624183,18.48
29,2026-07-08 00:52:16,Validacao Cruzada,"{'changepoint_prior_scale': 0.1, 'seasonality_...",972.525986,707.174695,NaN,0.177543,0.629412,15.16
30,2026-07-08 00:52:30,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'seasonality_...",828.521036,641.518014,NaN,0.151510,0.672549,13.98
31,2026-07-08 00:52:57,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'seasonality_...",830.147077,643.360684,NaN,0.150664,0.674510,26.63
32,2026-07-08 00:53:12,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'seasonality_...",833.285526,647.028552,NaN,0.150815,0.673203,13.83
33,2026-07-08 00:53:30,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'seasonality_...",1097.147552,774.562969,NaN,0.190660,0.690850,16.36
34,2026-07-08 00:53:50,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'seasonality_...",1126.670510,781.554660,NaN,0.180601,0.798693,20.22
35,2026-07-08 00:54:10,Validacao Cruzada,"{'changepoint_prior_scale': 0.5, 'seasonality_...",1127.230668,785.223794,NaN,0.183980,0.798693,19.45